### ISSUE TITLE
some api related errors 

### ISSUE THREAD

**Issue by Hiradpi** [Gozargah/Marzban-node#28]
the mode is manual i did not use docker and insted of setting env vars i set defualt vars in config.py 

```
root@minecraft:~/Marzban-node# netstat -tulnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      7473/sshd: /usr/sbi 
tcp6       0      0 :::22                   :::*                    LISTEN      7473/sshd: /usr/sbi 
udp        0      0 0.0.0.0:68              0.0.0.0:*                           451/dhclient        
root@minecraft:~/Marzban-node# nano docker-compose.yml 
root@minecraft:~/Marzban-node# nano config.py 
root@minecraft:~/Marzban-node# python main.py 
-bash: python: command not found
root@minecraft:~/Marzban-node# python3 main.py 
INFO: Node service running on :62050
WARNING: Connected to 1.1.1.123
DEBUG: Xray 1.8.6 (Xray, Penetrates Everything.) Custom (go1.21.4 linux/amd64)
DEBUG: A unified platform for anti-censorship.
DEBUG: 2023/12/26 20:48:14 [Info] infra/conf/serial: Reading config: stdin:
WARNING: Restarting Xray core...
WARNING: Xray core stopped
DEBUG: Xray 1.8.6 (Xray, Penetrates Everything.) Custom (go1.21.4 linux/amd64)
DEBUG: A unified platform for anti-censorship.
DEBUG: 2023/12/26 20:48:15 [Info] infra/conf/serial: Reading config: stdin:
DEBUG: 2023/12/26 20:48:16 [Info] transport/internet/websocket: listening TCP(for WS) on 0.0.0.0:2421
DEBUG: 2023/12/26 20:48:16 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:1080
DEBUG: 2023/12/26 20:48:16 [Info] transport/internet/udp: listening UDP on 0.0.0.0:1080
DEBUG: 2023/12/26 20:48:16 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:62051
DEBUG: 2023/12/26 20:48:16 [Info] transport/internet/websocket: listening TCP(for WS) on 0.0.0.0:3301
DEBUG: 2023/12/26 20:48:16 [Info] transport/internet/websocket: listening TCP(for WS) on 0.0.0.0:4430
DEBUG: 2023/12/26 20:48:16 [Info] transport/internet/websocket: listening TCP(for WS) on 0.0.0.0:8081
DEBUG: 2023/12/26 20:48:16 [Info] transport/internet/websocket: listening TCP(for WS) on 0.0.0.0:8080
DEBUG: 2023/12/26 20:48:16 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:1932
DEBUG: 2023/12/26 20:48:16 [Warning] core: Xray 1.8.6 started
DEBUG: 2023/12/26 20:48:17 [Info] [2047416402] proxy/dokodemo: received request for 1.1.1.123:38930
DEBUG: 2023/12/26 20:48:17 [Info] [2047416402] app/dispatcher: taking detour [API] for [tcp:127.0.0.1:0]
DEBUG: 2023/12/26 20:48:17 1.1.1.123:38930 accepted tcp:127.0.0.1:0 [API_INBOUND -> API]
DEBUG: 2023/12/26 20:48:20 [Info] [444798974] proxy/dokodemo: received request for 1.1.1.123:60750
DEBUG: 2023/12/26 20:48:20 [Info] [444798974] app/dispatcher: taking detour [API] for [tcp:127.0.0.1:0]
DEBUG: 2023/12/26 20:48:20 1.1.1.123:60750 accepted tcp:127.0.0.1:0 [API_INBOUND -> API]
WARNING: Disconnected from 1.1.1.123
WARNING: Xray core stopped
--- Logging error ---
Traceback (most recent call last):
  File "/root/Marzban-node/service.py", line 99, in on_stop
    self.connection.root.on_stop()
  File "/usr/local/lib/python3.9/dist-packages/rpyc/core/netref.py", line 148, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/usr/local/lib/python3.9/dist-packages/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/usr/local/lib/python3.9/dist-packages/rpyc/core/protocol.py", line 715, in sync_request
    _async_res = self.async_request(handler, *args, timeout=timeout)
  File "/usr/local/lib/python3.9/dist-packages/rpyc/core/protocol.py", line 742, in async_request
    self._async_request(handler, args, res)
  File "/usr/local/lib/python3.9/dist-packages/rpyc/core/protocol.py", line 724, in _async_request
    self._send(consts.MSG_REQUEST, seq, (handler, self._box(args)))
  File "/usr/local/lib/python3.9/dist-packages/rpyc/core/protocol.py", line 298, in _send
    self._channel.send(data)
  File "/usr/local/lib/python3.9/dist-packages/rpyc/core/channel.py", line 78, in send
    self.stream.write(header + data + self.FLUSHER)
  File "/usr/local/lib/python3.9/dist-packages/rpyc/core/stream.py", line 288, in write
    count = self.sock.send(data[:self.MAX_IO_CHUNK])
  File "/usr/local/lib/python3.9/dist-packages/rpyc/core/stream.py", line 96, in __getattr__
    raise EOFError("stream has been closed")
EOFError: stream has been closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/root/Marzban-node/logger.py", line 58, in format
    return formatter.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.9/threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Marzban-node/service.py", line 101, in on_stop
    logger.debug('Peer on_stop exception:', exc)
Message: 'Peer on_stop exception:'
Arguments: (EOFError('stream has been closed'),)
```

**Comment by Hiradpi** [comment]
and hese is the json responce i hope it helps i have been trying to set this up for almost 4 hours

```[
    {
        "name": "arvan",
        "address": "188.121.115.63",
        "port": 62050,
        "api_port": 62051,
        "usage_coefficient": 1.0,
        "id": 1,
        "xray_version": null,
        "status": "error",
        "message": "Failed to connect to node's API"
    }
]```

**Comment by parhawm** [comment]
what request is this json response to? 
and care to turn on debug logs for the main server and show them?
seems like the client(main server) is closing the connection for some reason after connecting. could also be a network problem

**Comment by Moondmn** [comment]
Marzban (and any another x-ray/v2ray panels) truly sucks. Basically every open source projects related to "Iran, China, Russia, and any other country in the world", is NOT worthy of existing.
It just doesn't worth it man.
Go and live in the woods
F this
Wait a sec, why am i even saying these here, i should be dead, gone or smth
Idk
ps. Bye pishi

**Comment by Hiradpi** [comment]
dude tf is wrong with you 
u ain't gonno gass up your ass car without us u ain't gonno be able to get a bottle of water without our governments help so stfu you don't matter your shitty country socks more than our 
at least our country executes faggots yours gives em rights frr

**Comment by Hiradpi** [comment]
tf

**Comment by NiiightmareXD** [comment]
Age pishi khubi budi intory nemishod!

**Comment by Hiradpi** [comment]
to chi migi rust developer gay 
fek kon project kiri python panel v2ray be esm marx ban az windows capture to bishtar star dashte bashe

**Comment by Hiradpi** [comment]
marzban*

**Comment by NiiightmareXD** [comment]
> to chi migi rust developer gay fek kon project kiri python panel v2ray be esm marx ban az windows capture to bishtar star dashte bashe

Biya kir mano bokhor skid no skill deserved to be in /dev/null pashmak zade babaye bozorg ye payam daram bara gorbe aziz 360 snipe LOL 220 headshot respectfully though .

**Comment by Hiradpi** [comment]
imagine my little pony niga koni baad beri rosh beshini bezani 
imagine rust dev bashi femboy bashi pedo bashi AI bashi gay bashi kooni bashi fortniteam play bedi 
koonam midi noonam migiri kil kharab kos jebhe

**Comment by Hiradpi** [comment]
age man to dev null am to too (hd0,gpt69)/null e

**Comment by parhawm** [comment]
بچه ها دعوا نکنید

**Comment by NiiightmareXD** [comment]
> imagine my little pony niga koni baad beri rosh beshini bezani imagine rust dev bashi femboy bashi pedo bashi AI bashi gay bashi kooni bashi fortniteam play bedi koonam midi noonam migiri kil kharab kos jebhe

Not only all the above are false (Except fortnite one) imagine kol zendegito tu r621 begzaruni

**Comment by NiiightmareXD** [comment]
> age man to dev null am to too (hd0,gpt69)/null e

Stfu average undefined enjoyer

**Comment by Hiradpi** [comment]
voice to mifrestam haminja bebinim chi false ha

**Comment by NiiightmareXD** [comment]
> voice to mifrestam haminja bebinim chi false ha

Voice chiye age video little pony mano ferestadi hale

**Comment by Hiradpi** [comment]
hale nude fire cracker o mifrestam aval

**Comment by NiiightmareXD** [comment]
> hale nude fire cracker o mifrestam aval

Hhhhhhhhh, pas nadari dige

**Comment by Hiradpi** [comment]
age enghadr fek mikoni khafani khodet boro ye panel benevis yekam useful bash

**Comment by parhawm** [comment]
moshkelet hal shod /dev/null?

**Comment by Moondmn** [comment]
> moshkelet hal shod /dev/null?

Kheir

**Comment by Hiradpi** [comment]
> moshkelet hal shod /dev/null?

are dadash asan alan enghadr moshkelam hal shode daram sie mikonam api e ro rewrite konam

**Comment by M03ED** [comment]
> are dadash asan alan enghadr moshkelam hal shode daram sie mikonam api e ro rewrite konam

به جای اذیت کردن خودت با داکر ران کن

**Comment by Hiradpi** [comment]
داکر گیه 
میروراش تا دسته تحریم کردن

**Comment by Hiradpi** [comment]
اون هیچ کلا داکر ریده

**Comment by M03ED** [comment]
> داکر گیه 
> میروراش تا دسته تحریم کردن 

docker pull ghcr.io/gozargah/marzban-node:v0.2.0

**Comment by Hiradpi** [comment]
ماشالا شما کانتربیوتر پروژه شما باشی همین میشه دیگه سرتیفیکیت اشتباه بدی به جا این که هندل کنه ارورایی میده میبینی میرینی 

بابا میگم میروراش تحریم کردن ما رو یعنی اینستالش نمیتونم بکنم

**Comment by M03ED** [comment]
من هیچ کانتربیوتی به مرزبان نود نداشتم 
شما هم به جای توهین کردن به بقیه یه مقدار اخلاق تون رو بهتر کنید
برای مشکل داکر هم قبلا آموزش رفع مشکل شو خودم نوشتم و تو مرزبان قرار دادم 
به درود.

**Comment by Habib1385** [comment]
@M03ED سلام 
برای مسخره بازی اومدن این دسته افراد توجه نکنید
