### ISSUE TITLE
connecting issues in Marzban-node 'NoneType' object has no attribute  errors

### ISSUE THREAD

**Issue by ImMohammad20000** [Gozargah/Marzban-node#31]
too many connecting issues in nodes

marzban nodes logs:

```
marzban-node-1  | client connection terminated abruptly
marzban-node-1  | Traceback (most recent call last):
marzban-node-1  |   File "/code/service.py", line 52, in on_connect
marzban-node-1  |     self.connection.ping()
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/protocol.py", line 253, in ping
marzban-node-1  |     if res.value != data:
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/async_.py", line 106, in value
marzban-node-1  |     self.wait()
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/async_.py", line 51, in wait
marzban-node-1  |     self._conn.serve(self._ttl)
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/protocol.py", line 434, in serve
marzban-node-1  |     data = self._channel.poll(timeout) and self._channel.recv()
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/channel.py", line 47, in poll
marzban-node-1  |     return self.stream.poll(timeout)
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/stream.py", line 45, in poll
marzban-node-1  |     p.register(self.fileno(), "r")
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/stream.py", line 255, in fileno
marzban-node-1  |     return self.sock.fileno()
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/stream.py", line 106, in fileno
marzban-node-1  |     raise EOFError("stream has been closed")
marzban-node-1  | EOFError: stream has been closed
marzban-node-1  |
marzban-node-1  | During handling of the above exception, another exception occurred:
marzban-node-1  |
marzban-node-1  | Traceback (most recent call last):
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/utils/server.py", line 183, in _authenticate_and_serve_client
marzban-node-1  |     self._serve_client(sock2, credentials)
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/utils/server.py", line 204, in _serve_client
marzban-node-1  |     conn = self.service._connect(Channel(SocketStream(sock)), config)
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/service.py", line 106, in _connect
marzban-node-1  |     self.on_connect(conn)
marzban-node-1  |   File "/code/service.py", line 56, in on_connect
marzban-node-1  |     logger.warning(f'Previous connection from {self.connection.peer} has lost')
marzban-node-1  | AttributeError: 'NoneType' object has no attribute 'peer'
marzban-node-1  | Exception in thread RpycSpawnThread-builtins.method-139874169288000-139874137427008:
marzban-node-1  | Traceback (most recent call last):
marzban-node-1  |   File "/code/service.py", line 52, in on_connect
marzban-node-1  |     self.connection.ping()
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/protocol.py", line 253, in ping
marzban-node-1  |     if res.value != data:
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/async_.py", line 106, in value
marzban-node-1  |     self.wait()
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/async_.py", line 51, in wait
marzban-node-1  |     self._conn.serve(self._ttl)
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/protocol.py", line 434, in serve
marzban-node-1  |     data = self._channel.poll(timeout) and self._channel.recv()
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/channel.py", line 47, in poll
marzban-node-1  |     return self.stream.poll(timeout)
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/stream.py", line 45, in poll
marzban-node-1  |     p.register(self.fileno(), "r")
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/stream.py", line 255, in fileno
marzban-node-1  |     return self.sock.fileno()
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/stream.py", line 106, in fileno
marzban-node-1  |     raise EOFError("stream has been closed")
marzban-node-1  | EOFError: stream has been closed
marzban-node-1  |
marzban-node-1  | During handling of the above exception, another exception occurred:
marzban-node-1  |
marzban-node-1  | Traceback (most recent call last):
marzban-node-1  |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
marzban-node-1  |     self.run()
marzban-node-1  |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
marzban-node-1  |     self._target(*self._args, **self._kwargs)
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/utils/server.py", line 183, in _authenticate_and_serve_client
marzban-node-1  |     self._serve_client(sock2, credentials)
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/utils/server.py", line 204, in _serve_client
marzban-node-1  |     conn = self.service._connect(Channel(SocketStream(sock)), config)
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/service.py", line 106, in _connect
marzban-node-1  |     self.on_connect(conn)
marzban-node-1  |   File "/code/service.py", line 56, in on_connect
marzban-node-1  |     logger.warning(f'Previous connection from {self.connection.peer} has lost')
marzban-node-1  | AttributeError: 'NoneType' object has no attribute 'peer'
marzban-node-1  | WARNING: Connected to IP
marzban-node-1  | WARNING: Disconnected from IP
marzban-node-1  | WARNING: Xray core stopped
marzban-node-1  | WARNING: Connected to IP
marzban-node-1  | WARNING: Disconnected from IP
marzban-node-1  | WARNING: Xray core stopped
marzban-node-1  | WARNING: Connected to IP
marzban-node-1  | WARNING: New connection rejected, already connected to IP
marzban-node-1  | WARNING: New connection rejected, already connected to IP
marzban-node-1  | WARNING: Previous connection from IP has lost
marzban-node-1  | WARNING: Connected to IP
marzban-node-1  | WARNING: Disconnected from IP
marzban-node-1  | ERROR: 'NoneType' object has no attribute 'on_stop'
marzban-node-1  | client connection terminated abruptly
marzban-node-1  | Traceback (most recent call last):
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/utils/server.py", line 183, in _authenticate_and_serve_client
marzban-node-1  |     self._serve_client(sock2, credentials)
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/utils/server.py", line 204, in _serve_client
marzban-node-1  |     conn = self.service._connect(Channel(SocketStream(sock)), config)
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/service.py", line 106, in _connect
marzban-node-1  |     self.on_connect(conn)
marzban-node-1  |   File "/code/service.py", line 53, in on_connect
marzban-node-1  |     logger.warning(f'New connection rejected, already connected to {self.connection.peer}')
marzban-node-1  | AttributeError: 'NoneType' object has no attribute 'peer'
marzban-node-1  | Exception in thread RpycSpawnThread-builtins.method-139874169288000-139874121129920:
marzban-node-1  | Traceback (most recent call last):
marzban-node-1  |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
marzban-node-1  |     self.run()
marzban-node-1  |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
marzban-node-1  |     self._target(*self._args, **self._kwargs)
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/utils/server.py", line 183, in _authenticate_and_serve_client
marzban-node-1  |     self._serve_client(sock2, credentials)
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/utils/server.py", line 204, in _serve_client
marzban-node-1  |     conn = self.service._connect(Channel(SocketStream(sock)), config)
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/service.py", line 106, in _connect
marzban-node-1  |     self.on_connect(conn)
marzban-node-1  |   File "/code/service.py", line 53, in on_connect
marzban-node-1  |     logger.warning(f'New connection rejected, already connected to {self.connection.peer}')
marzban-node-1  | AttributeError: 'NoneType' object has no attribute 'peer'

```

any idea how to fix it?

**Comment by ImMohammad20000** [comment]
another error is this

```
'NoneType' object has no attribute 'peer'
 ========= Remote Traceback (1) ========= Traceback (most recent call last): 
File "/usr/local/lib/python3.10/site-packages/rpyc/core/protocol.py", line 356, in _dispatch_request res = self._HANDLERS[handler](self, *args) 
File "/usr/local/lib/python3.10/site-packages/rpyc/core/protocol.py", line 837, in _handle_call return obj(*args, **dict(kwargs)) 
File "/code/service.py", line 124, in restart config = XRayConfig(config, self.connection.peer) 
AttributeError: 'NoneType' object has no attribute 'peer'


```

**Comment by ImMohammad20000** [comment]
and 

```
'NoneType' object has no attribute 'restart' 
========= Remote Traceback (1) ========= Traceback (most recent call last): 
File "/usr/local/lib/python3.10/site-packages/rpyc/core/protocol.py", line 356, in _dispatch_request res = self._HANDLERS[handler](self, *args) 
File "/usr/local/lib/python3.10/site-packages/rpyc/core/protocol.py", line 837, in _handle_call return obj(*args, **dict(kwargs)) 
File "/code/service.py", line 125, in restart self.core.restart(config) 
AttributeError: 'NoneType' object has no attribute 'restart'
```

**Comment by ImMohammad20000** [comment]
if we can fix this 3 issues nodes will be stabled and work bether

**Comment by m0x61h0x64i** [comment]
https://github.com/Gozargah/Marzban-node/issues/46
