### ISSUE TITLE
ریستارت شدن مکرر و همزمان نود ها

### ISSUE THREAD

**Issue by m0x61h0x64i** [Gozargah/Marzban-node#46]
سلام، این لاگ نود
```
marzban-node-1  | INFO: 91.107.*** connected, Session ID = "07e9563c-1767-4129-8095-0657ae09c3e5".
marzban-node-1  | INFO:     91.107.***:59386 - "POST /connect HTTP/1.1" 200 OK
marzban-node-1  | INFO:     91.107.***:50330 - "POST /ping HTTP/1.1" 403 Forbidden
marzban-node-1  | INFO:     91.107.***:50330 - "POST /ping HTTP/1.1" 403 Forbidden
marzban-node-1  | INFO:     91.107.***:50330 - "POST /ping HTTP/1.1" 403 Forbidden
marzban-node-1  | INFO: 91.107.*** disconnected, Session ID = "07e9563c-1767-4129-8095-0657ae09c3e5".
marzban-node-1  | WARNING: Xray core stopped
marzban-node-1  | INFO:     91.107.***:50330 - "POST /disconnect HTTP/1.1" 200 OK
marzban-node-1  | INFO: 91.107.*** connected, Session ID = "a6614128-2334-4668-a183-92d168776d4a".
marzban-node-1  | INFO:     91.107.***:59404 - "POST /connect HTTP/1.1" 200 OK
marzban-node-1  | INFO:     91.107.***:59386 - "POST /start HTTP/1.1" 200 OK
marzban-node-1  | INFO:     91.107.***:59386 - "POST / HTTP/1.1" 200 OK
marzban-node-1  | INFO:     91.107.***:59404 - "POST /start HTTP/1.1" 200 OK
marzban-node-1  | INFO:     91.107.***:59404 - "POST / HTTP/1.1" 200 OK
marzban-node-1  | INFO:     91.107.***:59386 - "POST /ping HTTP/1.1" 403 Forbidden
marzban-node-1  | INFO:     91.107.***:58776 - "POST /ping HTTP/1.1" 403 Forbidden
marzban-node-1  | INFO:     91.107.***:58776 - "POST /ping HTTP/1.1" 403 Forbidden
marzban-node-1  | INFO:     91.107.***:58776 - "POST /ping HTTP/1.1" 403 Forbidden
marzban-node-1  | INFO:     91.107.***:59404 - "POST /ping HTTP/1.1" 200 OK
marzban-node-1  | INFO:     91.107.***:59404 - "POST / HTTP/1.1" 200 OK
marzban-node-1  | INFO:     91.107.***:58776 - "POST /ping HTTP/1.1" 403 Forbidden
marzban-node-1  | INFO: 91.107.*** disconnected, Session ID = "a6614128-2334-4668-a183-92d168776d4a".
marzban-node-1  | WARNING: Xray core stopped
marzban-node-1  | INFO:     91.107.***:58776 - "POST /disconnect HTTP/1.1" 200 OK
marzban-node-1  | INFO: 91.107.*** connected, Session ID = "08a665fa-7d98-413e-a143-ca79677ac82b".
marzban-node-1  | INFO:     91.107.***:58796 - "POST /connect HTTP/1.1" 200 OK
marzban-node-1  | INFO:     91.107.***:59404 - "POST /ping HTTP/1.1" 403 Forbidden
marzban-node-1  | INFO:     91.107.***:59404 - "POST /ping HTTP/1.1" 403 Forbidden
marzban-node-1  | INFO:     91.107.***:59404 - "POST /ping HTTP/1.1" 403 Forbidden
marzban-node-1  | INFO: 91.107.*** disconnected, Session ID = "08a665fa-7d98-413e-a143-ca79677ac82b".
marzban-node-1  | WARNING: Xray core stopped
marzban-node-1  | INFO:     91.107.***:59404 - "POST /disconnect HTTP/1.1" 200 OK
marzban-node-1  | INFO: 91.107.*** connected, Session ID = "1fc6e25b-2bae-4b53-8a84-6356f59ec3ee".
marzban-node-1  | INFO:     91.107.***:58834 - "POST /connect HTTP/1.1" 200 OK
marzban-node-1  | INFO:     91.107.***:58796 - "POST /start HTTP/1.1" 200 OK
marzban-node-1  | INFO:     91.107.***:58796 - "POST / HTTP/1.1" 200 OK
marzban-node-1  | INFO:     91.107.***:58834 - "POST /start HTTP/1.1" 200 OK
marzban-node-1  | INFO:     91.107.***:58834 - "POST / HTTP/1.1" 200 OK
```

از کجا میفهمم که اصن نودا همزمان کانکتینگ میشه؟ توی پنل

از لاگ های پنل هم مشخص هست:
```
marzban-1     | INFO:     Connecting to "falkenstein" node
marzban-1     | INFO:     Connecting to "falkenstein-2" node
marzban-1     | INFO:     Connected to "falkenstein-3" node, xray run on v1.8.10
marzban-1     | INFO:     Connected to "falkenstein" node, xray run on v1.8.10
marzban-1     | INFO:     Connected to "falkenstein-2" node, xray run on v1.8.10
marzban-1     | INFO:     Connecting to "falkenstein-3" node
marzban-1     | INFO:     Connecting to "falkenstein" node
marzban-1     | INFO:     Connecting to "falkenstein-2" node
marzban-1     | INFO:     Connected to "falkenstein-3" node, xray run on v1.8.10
marzban-1     | INFO:     Connected to "falkenstein-2" node, xray run on v1.8.10
marzban-1     | INFO:     Connected to "falkenstein" node, xray run on v1.8.10
marzban-1     | INFO:     Connecting to "falkenstein-3" node
marzban-1     | INFO:     Connecting to "falkenstein" node
marzban-1     | INFO:     Connecting to "falkenstein-2" node
marzban-1     | INFO:     Connected to "falkenstein-3" node, xray run on v1.8.10
marzban-1     | INFO:     Connected to "falkenstein" node, xray run on v1.8.10
marzban-1     | INFO:     Connected to "falkenstein-2" node, xray run on v1.8.10
marzban-1     | INFO:     Connecting to "falkenstein-3" node
marzban-1     | INFO:     Connecting to "falkenstein" node
marzban-1     | INFO:     Connecting to "falkenstein-2" node
marzban-1     | INFO:     Connected to "falkenstein-3" node, xray run on v1.8.10
marzban-1     | INFO:     Connected to "falkenstein" node, xray run on v1.8.10
marzban-1     | INFO:     Connected to "falkenstein-2" node, xray run on v1.8.10
```

همه اخرین ورژن و پروتکل rest استفاده میکنم

**Comment by m0x61h0x64i** [comment]
SERVICE_PROTOCOL: "rest" 
رو کامنت کردم درست شد :/

**Comment by m0x61h0x64i** [comment]
امروز که rest نداشتم این ارور رو گرفتم بعد xray code stop شد
```
marzban-node-1  | client connection terminated abruptly
marzban-node-1  | Traceback (most recent call last):
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/utils/server.py", line 183, in _authenticate_and_serve_client
marzban-node-1  |     self._serve_client(sock2, credentials)
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/utils/server.py", line 204, in _serve_client
marzban-node-1  |     conn = self.service._connect(Channel(SocketStream(sock)), config)
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/service.py", line 106, in _connect
marzban-node-1  |     self.on_connect(conn)
marzban-node-1  |   File "/code/rpyc_service.py", line 62, in on_connect
marzban-node-1  |     peer, _ = socket.getpeername(conn._channel.stream.sock)
marzban-node-1  | OSError: [Errno 107] Transport endpoint is not connected
marzban-node-1  | Exception in thread RpycSpawnThread-builtins.method-139619962852672-139619883320448:
marzban-node-1  | Traceback (most recent call last):
marzban-node-1  |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
marzban-node-1  |     self.run()
marzban-node-1  |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
marzban-node-1  |     self._target(*self._args, **self._kwargs)
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/utils/server.py", line 183, in _authenticate_and_serve_client
marzban-node-1  |     self._serve_client(sock2, credentials)
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/utils/server.py", line 204, in _serve_client
marzban-node-1  |     conn = self.service._connect(Channel(SocketStream(sock)), config)
marzban-node-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/service.py", line 106, in _connect
marzban-node-1  |     self.on_connect(conn)
marzban-node-1  |   File "/code/rpyc_service.py", line 62, in on_connect
marzban-node-1  |     peer, _ = socket.getpeername(conn._channel.stream.sock)
marzban-node-1  | OSError: [Errno 107] Transport endpoint is not connected
```

**Comment by m0x61h0x64i** [comment]
توی پنل اپدیت نود رو که میزنم همین خطا مجدد روی سرور نود میاد:
```
WARNING: Disconnected from 91.107.165.***
WARNING: Xray core stopped
client connection terminated abruptly
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/rpyc/utils/server.py", line 183, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "/usr/local/lib/python3.10/site-packages/rpyc/utils/server.py", line 204, in _serve_client
    conn = self.service._connect(Channel(SocketStream(sock)), config)
  File "/usr/local/lib/python3.10/site-packages/rpyc/core/service.py", line 106, in _connect
    self.on_connect(conn)
  File "/code/rpyc_service.py", line 62, in on_connect
    peer, _ = socket.getpeername(conn._channel.stream.sock)
OSError: [Errno 107] Transport endpoint is not connected
Exception in thread RpycSpawnThread-builtins.method-139719065707840-139719012799936:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/rpyc/utils/server.py", line 183, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "/usr/local/lib/python3.10/site-packages/rpyc/utils/server.py", line 204, in _serve_client
    conn = self.service._connect(Channel(SocketStream(sock)), config)
  File "/usr/local/lib/python3.10/site-packages/rpyc/core/service.py", line 106, in _connect
    self.on_connect(conn)
  File "/code/rpyc_service.py", line 62, in on_connect
    peer, _ = socket.getpeername(conn._channel.stream.sock)
OSError: [Errno 107] Transport endpoint is not connected
WARNING: Connected to 91.107.165.***
```

**Comment by m0x61h0x64i** [comment]
سرور از نو ساخته بودم فقط اینو زدم برای نصب :
`apt update && apt upgrade -y && apt install socat -y && apt install curl socat -y && apt install git -y && cd .. && git clone https://github.com/Gozargah/Marzban-node && cd Marzban-node && curl -fsSL https://get.docker.com | sh && docker compose up -d`

**Comment by m0x61h0x64i** [comment]
حتی سرور نود رو ریبیلد میکنم از نو نصب انجام میدم داخل پنل هم قبلش نودو پاک کردم از اخر مجدد نود ساختم بازم این ارور میده:
```
WARNING: You are running node without SSL_CLIENT_CERT_FILE, be aware that everyone can connect to this node and this isn't secure!
INFO: Node service running on :62050
client connection terminated abruptly
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/rpyc/utils/server.py", line 183, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "/usr/local/lib/python3.10/site-packages/rpyc/utils/server.py", line 204, in _serve_client
    conn = self.service._connect(Channel(SocketStream(sock)), config)
  File "/usr/local/lib/python3.10/site-packages/rpyc/core/service.py", line 106, in _connect
    self.on_connect(conn)
  File "/code/rpyc_service.py", line 62, in on_connect
    peer, _ = socket.getpeername(conn._channel.stream.sock)
OSError: [Errno 107] Transport endpoint is not connected
Exception in thread RpycSpawnThread-builtins.method-139829003150656-139828967153856:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/rpyc/utils/server.py", line 183, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "/usr/local/lib/python3.10/site-packages/rpyc/utils/server.py", line 204, in _serve_client
    conn = self.service._connect(Channel(SocketStream(sock)), config)
  File "/usr/local/lib/python3.10/site-packages/rpyc/core/service.py", line 106, in _connect
    self.on_connect(conn)
  File "/code/rpyc_service.py", line 62, in on_connect
    peer, _ = socket.getpeername(conn._channel.stream.sock)
OSError: [Errno 107] Transport endpoint is not connected
WARNING: Connected to 91.107.165.***
WARNING: Restarting Xray core...
WARNING: Xray core stopped
```

**Comment by m0x61h0x64i** [comment]
الان نود رو با این اسکریپت نصب کردم (که پروتکل رو روی rest میزاره) همون مشکل قطع و وصلی نود به وجود میاد + کانفیگ ها کار نمیکنن
```
bash <(curl -Ls https://github.com/mikeesierrah/Marzban-scripts/raw/master/marzban-node.sh)
```

**Comment by Cmd81** [comment]
سلام داداش
منم این مشکل قطع و وصل شدن نود هارو دارم و با ریستارت هسته اوکی میشه . شما به نتیجه ای رسیدی؟

**Comment by m0x61h0x64i** [comment]
@Cmd81 
سلام. نه والا پاره شدم هیچکس هم پاسخگو نیست
